{% set name = "rowan" %}
{% set version = "1.2.0" %}
{% set sha256 = "f9f7f092b1e3c5b5fdfd193f3e4a2f989ea1efe52e7c07c5a2f33863914fbe9f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy>=1.10
    - scipy

test:
  imports:
    - rowan
    - rowan.mapping
    - rowan.geometry
    - rowan.calculus
    - rowan.interpolate
    - rowan.random

about:
  home: https://github.com/glotzerlab/rowan
  license: BSD-3
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Perform quaternion operations using numpy arrays'

  description: |
    rowan performs quaternion operations directly on numpy arrays.
    The package does not require conversion of arrays into a special
    quaternion object, ensuring easy integration into existing code,
    but broadcasting is fully supported natively for all operations to
    ensure that code is performant.
  doc_url: http://rowan.readthedocs.io/
  dev_url: https://github.com/glotzerlab/rowan

extra:
  recipe-maintainers:
    - vyasr
    - joaander
    - bdice
