travis:
  secure:
    BINSTAR_TOKEN: ZVSAWwUpvnXFgIHNU6BfmaDQ6WpmXRJWaxEuIrQCfkEJG804ftqd8EO3zMRRef75Tst/HjjkPQuhj+jnO8yAGu/SLWOkHMLtaIxdcTEgEgAIuwcSMMb4iiRoJcq/tG7mc/sxWEp4X/oyBbsC7VpIMhyqoI4/ETOThZYiu8mYFtO/LRK9NtA0jksz9l5W/6QJRE4yTzT0HaBj2B6SV9G0PR0jftoa6KSFxZmY+4TjqnoNtMJLHTdm8I+dSbC5U/44FJO6a5/urcPiYEGVZsqVyu/ef0r9t5i4N96yUE/pemu+OaLxR09CbpsJj2hoZ1iIxm/mfeWoRQ/Hcj+sBee27jJ7tmuZ/hFLRhkpc+J3lkMyYe8jomk4r1lscytoYEfHWOE6pBsfikKIZZHSHNKpKkACgCQB/3X/V/EDZnf/T2VDKGKf8cR6kBu2Md33RhvNdjIQZDWO82Vy71uD7OaBocJD/ak5D/UH56u8Y9fM8h9c2KsvTqJPYEkspaoNIHI5cGvaSMy6EIEbhFpDj7+w4iEVmhwyzB9C5mRbZBjVSVlr+qDlYxDvUrfyCHT1v08goZ6z8K6IRXaiAtBemgJuER6Yd7JXDoZCQWO5ntFd4FjVhao0A3J3Wy6NqYBDVWSwMj7Wm1lUp2rKgd33C7YRiaHCUzF2FPygz0AUVB3XOXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
